name: Build Plugin cho Vui
on:
  push:
    branches:
      - main

permissions:
  contents: write  # Cấp quyền ghi để tạo nhánh gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Build Plugin
        run: |
          # Dùng npx để tự động tải và chạy vd-cli mà không cần cài đặt rườm rà
          npx vd-cli build
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
          clean: true
          
